<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Paper Trail</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="styles.css">
    </head>
    <article>
        <div class="storyInfo">
            <h2>
                ELON MUSK’S TOTALLY AWFUL, BATSHIT-CRAZY, COMPLETELY BONKERS, MOST EXCELLENT YEAR
            </h2>
            <h4>
                In 2020, the COVID-doubting, media-hating Twitterholic CEO became the third-richest man alive, SpaceX launched two astronauts into orbit, and Tesla became the most valuable car company on the planet. Inside the mind of Silicon Valley’s most vainglorious villain.
            </h4>
        </div>
        <div class="storyMain">
            <img id="elon" src="elon.jpg" alt="Elon Musk illustration">
            <p>
                Elon Musk is on a mission. He’s on a mission to Mars. He’s on a mission to save humanity from its reliance on fossil fuels, which could destroy the planet and kill us all. He’s on a mission to save us from artificial intelligence algorithms going rogue and machines ending human life as we know it. He’s on a mission to help save a group of boys trapped underground in Thailand. A mission to transport people from Los Angeles to San Francisco in giant air tubes. A mission to build ventilators for hamstrung hospitals during the coronavirus pandemic. He’s on a mission to prove the coronavirus fatality rate is greatly overstated. To dig tunnels underground to alleviate the fatuous cycle of traffic jams. To save journalism. To mitigate the effects of climate change. To transport people in earthbound rockets from one continent to the next in mere minutes. To inhabit other planets before the sun explodes and turns our oceans into boiling vats of water, our skies into steam-filled death, our lands into carbon crusts of darkness. He’s on a mission to inhabit other star systems. All of these missions are completely possible in the realm of physics and science, especially with Elon Musk’s brain working to solve these problems.
            </p>
            <p>
                But this year, Musk set off on the most difficult mission of all. An expedition that has nothing to do with space, or fossil fuels, or coronavirus, or saving the lives of 7.7 billion people. And yet this new mission—unlike the long list of other tasks he plans to accomplish in his lifetime—is one that he may not be able to see through. A mission that, perhaps, no one of his stature has ever been able to accomplish. One that plagued Steve Jobs before he died. One that still afflicts Jack Dorsey each day. A mission that has sickened men and women since the dawn of modern civilization, kings, queens, business leaders, and politicians alike. A mission that may prove to be the most difficult one of his entire life: Elon Musk is on a mission to stop giving a shit what people think of him.
            </p>
            <p>
                Anyone who has paid even the slightest notice to Musk and his career over the past three decades—a series of vocations that would be almost impossible not to notice—is acutely aware that the 49-year-old entrepreneur, carmaker, and rocket scientist is arguably one of the most capable CEOs on the planet, and is not merely changing the world but the very fabric of the universe. He started the most successful private rocket company in history and the most successful car company in the world, as well as a controversial solar provider. Lately, he has been building tunnels under Las Vegas to alleviate traffic and exploring doing the same in Los Angeles, Baltimore, and Chicago, while overseeing Neuralink, a company that wants to, eventually, plant computer chips in our brains, and recording a rap song that now has millions of listens. When I spoke to more than a dozen people who know him, both personally and professionally, irrelevant of whether they love him or hate him (or both), most described Musk as a true genius. One simply said, “I’ve worked all over Silicon Valley, with some of the brightest minds in the world, and there’s only one person I would consider a true genius, who is head and shoulders the smartest guy in the room, and that is Elon.” In addition to his superhuman abilities, Musk is an “excellent father” (according to some close to him) and the third-richest person on the planet, worth around $108 billion as of October. As a result, he has been on the cover of almost every mainstream magazine in the world, including Wired, Time, The Atlantic, Newsweek, Fortune, Rolling Stone, and even Edibles Magazine.
            </p>
            <p>
                Yet, over the past year, a man who has done all of this before he has even turned 50 seems pained. Like something has been gnawing away at him. At times, he even seems like he’s on the edge of madness. An artist moments away from cutting off his own ear and dropping it in a mailbox, or perhaps posting a picture of it on Twitter. To us mere mortals this seems strange, given that, in 2020—the darkest year in modern history—Musk has accomplished more than almost any of us will achieve in our lifetimes. And yet, even as he is making good on his promises to deliver us from ourselves, his mission to do the same for himself is proving to be far more difficult.
            </p>
            <p>
                Every culture, and every era in time, has its legends. The Chinese praised the great warriors and warlords who controlled the Asian empire. The Polynesians worshipped the gods who supplied them with fish. In Europe, those who set off to find new lands were knighted and had entire armadas named after them. Yet in the relatively infantile United States of America, folklore and luminescence has bounced from one type of deity (or false idol) to the next. Politicians, once respected for changing the tides of society by beating back the axis of evil, are now mostly parodies of reality TV. Bankers, once idolized for their wealth, are now vilified and detested by the proletariat. Journalists with last names like Cronkite and Gellhorn have seen their professions bastardized by Hannitys and Ingrahams. As of late, the most idolized in America have become the ones who are now partially destroying it: the tech titans. One by one, they’ve been built up as gods among us. Steve Jobs, Sergey Brin, Marissa Mayer, and Jeff Bezos, to name a few, had virtual statues of them erected in digital squares, which were then systematically spray-painted, dismantled, and tossed over a bridge as their true dualities came to light. This year, it seems, it was Musk’s turn.
            </p>
            <p>
                At the forefront of the ire against Musk was his attempt to disprove the severity of the coronavirus at the height of the pandemic by downplaying the number of deaths and railing against America’s decision to go into lockdown. This is partially, of course, due to the fact that shelter-in-place orders shuttered Musk’s Tesla factory right when it was getting into a production groove. But his puerile approach to disagreeing with the response to COVID-19, and his disregard and denigration of true experts, aligned him with Donald Trump and his alt-right supporters, making Musk a pariah to the other half of the country that once revered him. On a Tesla earnings call, Musk stoked the fires, calling the shelter-in-place orders “fascist” and “not democratic.” He told the bro-friendly Joe Rogan that the actual mortality rate from coronavirus differed from projections “by at least a factor of 10, maybe a factor of 50.” (A statement that is completely fabricated.) But while Musk was playing the coronavirus skeptic in public, things were playing out differently in private. One person confided that Musk told them he was canceling trips to Asia due to COVID concerns. By May, seemingly fed up with Musk’s antics, the tide seemed to change enough that supporting him was akin to supporting Trump. This was exemplified when former U.S. Attorney for the Southern District of New York Preet Bharara tweeted, “It feels good to unfollow @elonmusk.”
            </p>
            <p>
                The turn from Musk, savior of the human race, to “What the fuck is wrong with Elon Musk?!”—a question that is constantly posed to me—began back in 2018, in what people internally at Tesla and SpaceX refer to as “the Summer of 420,” according to two former executives. Musk, at the time, was constantly irked by the fact that Wall Street was shorting Tesla stock by more than a quarter billion dollars, with more people betting against Tesla (and, in turn, Musk) than any other company in the United States, according to financial technology and analytics firm S3 Partners LLC. (Over the years covering Musk and his companies, numerous employees have told me Musk sees the shorting of his stock as especially egregious, given that Tesla is trying to help save the planet by ending our reliance on fossil fuels.) As the story now goes, on August 7 of that year, while driving to the airport, Musk tweeted, “Am considering taking Tesla private at $420. Funding secured.” Indeed, that turned out to be untrue. (The number 420, a weed reference, was chosen as a joke.) Less than a month earlier, he had called a cave rescuer in Thailand “pedo guy” and was becoming increasingly erratic on earnings calls, on social media, and in interviews. By September, he got high and drunk (or at least tipsy) on the Joe Rogan Experience, smoking a joint and drinking whiskey.
            </p>
            <p>
                To everyone watching, it seemed as if Musk was finally unraveling from the pressure of his mission to save the world. “The thing about Elon is, that right now, everyone else is finally seeing the way he has always been,” said a former Tesla executive who worked with Musk for years. “He’s being the same Elon he has always been in private.” Now, this past year, “he’s just being Elon a lot more publicly.” Some people close to him believe his erratic behavior in 2020 was even more on display because he has taken to substances, including alcohol and marijuana, which he obsesses about on social media, or LSD, as the singer Azealia Banks has claimed (and Musk has denied), or Ambien, which the board of Tesla has reportedly worried over.
            </p>
            <p>
                “EVERYONE ELSE IS <strong>FINALLY SEEING</strong> THE WAY HE HAS <strong>ALWAYS BEEN.</strong> HE’S BEING <strong>THE SAME</strong> HE HAS ALWAYS BEEN IN <strong>PRIVATE.</strong> HE’S JUST BEING ELON A LOT <strong>MORE PUBLICLY.</strong>”
            </p>
            <p>
                Whatever his drug of choice, several executives have told me that employees at all of his companies check Musk’s Twitter account first thing in the morning to see what disaster happened the night before—and to decipher if it will lead to a new lawsuit, affect Tesla’s stock price, or add to growing public resentment toward their CEO. “We all wake up and look at it every day, thinking, Oh, God, now what? You really had no idea what you were going to see,” one former employee said. At SpaceX and Tesla, another Tesla executive told me, employees from both companies keep one another abreast of Musk’s moods so that they’ll know if Dr. Jekyll or Mr. Hyde is coming into the office that day. “On [SpaceX] launch days, you have everyone at Tesla tuned in to see if the launch is successful, not because we are vested in the rockets, but because it directly impacts Elon’s mood for the next few days,” the Tesla executive told me. “If there was a failure on a launch, there’d be hell to pay; you didn’t want to have a phone call set up with Elon afterward.” On the other hand, if the rocket launch was successful, Musk’s inbox would fill with budget requests. The same is true for SpaceX employees when new production numbers are set to be released for Tesla.
            </p>
            <p>
                In the past, Musk’s ire outside his companies was usually pointed toward authority, for which he has little patience and disregards as if the world we live in, and the rules that govern it, don’t apply to him and his companies. Musk simply hung up on the National Transportation Safety Board chairman when discussing a fatal Tesla autopilot accident. On earnings calls this year, he has constantly interrupted analysts. After his debacle in the Summer of 420, he was charged with fraud by the SEC, but couldn’t leave it alone, and referred to the agency as the “Shortseller Enrichment Commission.” Musk eventually settled with the SEC, agreeing to step down as Tesla’s chairman and pay $40 million in penalties. By spring of this year, when shelter-in-place orders were issued in Alameda County, where Musk’s Tesla Fremont plant is located, he refused to send employees home. After finally relenting, he went on a Twitter tirade, threatening to sue the county and even to leave California altogether before he got his way and the plant was reopened.
            </p>
            <p>
                This wayward behavior is on display in his personal life too. According to one person who witnessed an argument between Musk and a former girlfriend upon leaving a club one evening, Musk aggressively railed against her, asking why she had hair on her face (referring to the slight peach fuzz that everyone has, visible under the bright light of the club’s awning). “Because I’m a mammal,” the girlfriend replied, which only pissed Musk off even more.
            </p>
            <p>
                “There is a high level of degenerate behavior with Elon,” one person who knows Musk told me. “There’s a paranoia: Are you with me or against me?” Musk’s hyper energy is sometimes uncomfortable to be around, this person added: “I genuinely want to leave the room sometimes when he walks in.” And, while he can even come across as a “bully,” they noted that Musk is not alone among tech titans in this character trait. “All of these guys, I’ve spent time with them, Musk, Zuck, all of them; they all exhibit tendencies of total and complete pathological sociopathy. They don’t at their core give a flying fuck about you or me as individuals.”
            </p>
            <p>
                They do, however, all seem to give a shit what people think of them. Usually, when the tides of praise turn against someone of such stature, they hire consultants, lobbyists, and public relations firms to get them puff pieces in national news outlets, or they agree to give talks at major tech conferences, as long as the questions are little bitty softballs. Most of these CEOs and tech leaders are so obsessed with their image that they employ armies of communications experts, who help craft their brilliance for all to see. Executives I’ve covered in Silicon Valley almost always have teams prep them for interviews with long lists of all the possible questions they might be asked, and a long list of highly scrutinized answers.
            </p>
            <p>
                Yet, after the Summer of 420, Musk has taken on a completely different approach. One that is unlike anyone else at his level, and one that, some argue, is working out better than he ever could have imagined.
            </p>
            <p>
                The afternoon of December 6, 2019, was one of the most defining moments in Musk’s decades-long career, according to several people close to him. It wasn’t one of his most daunting missions into space, or yet another impregnable project with electric cars or brain implants or underground tunnels. Rather, it was a mission involving—what else?—a tweet. Musk had spent the previous year and a half trying to, at times, rewrite the reasoning for his tweet accusing a British cave explorer who had helped rescue a dozen boys trapped in a Thai cave of being a pedophile. At other times, Musk had tried to justify the tweet’s existence. The whole debacle culminated in a lawsuit by the cave explorer, Vernon Unsworth, and that afternoon in 2019, a verdict was due as to whether Musk should pay Unsworth damages (and, more importantly to the billionaire, be perceived as being wrong). Musk was surrounded by his personal security guards as he set off to the U.S. district courthouse in Los Angeles. Most people on the periphery of the case had assumed Musk would surely lose. But as luck (or money, given the price tag of the law firm Musk used to defend his tweet) would have it, he ended up winning. As he walked out of the courthouse, clearly relieved, having completed yet another mission, he told a gaggle of reporters, “My faith in humanity is restored.” And then he did something completely out of the ordinary.
            </p>
            <p>
                Musk went to Twitter and started blocking many of the reporters who had covered the trial or who covered his companies, including Ryan Mac of BuzzFeed, Lora Kolodny of CNBC, and Dana Hull, who covers Tesla and SpaceX for Bloomberg. A move that no other CEO of a Fortune 500 company is known to have made.
            </p>
            <p>
                According to one person who worked with Musk through this whole escapade, he decided shortly after he won the case that he was finished trying to be nice to the journalists, seeing them as biased against him. (How very Trump of him.) What’s more, he decided he was done being nice to anyone else who didn’t agree with him. He had spent his entire career trying to pretend he gave a shit about what people thought of him, and he was done. He soon parted ways with a public relations firm he worked with, he didn’t fill positions in his communications division when people left, and, as this person said, “Elon is his own communications director now.” When reached for comment on this article, he responded, “Vanity Fair sucks,” attributing the quote very clearly to himself.
            </p>
            <p>
                Over the years Musk has sometimes attacked the credibility of journalists, but as 2020 wore on, he went even further. He started to take on some of Trump’s tricks with the media, saying things publicly like “The Onion may be the best mainstream media source.” And in the same way that Trump soured on CNN and (mostly) only shared news clips from Fox News, and then soured on Fox News, only sharing clips from even more conservative outlets like One America News Network, Musk almost exclusively tweets links to heavily pro Tesla websites, like Teslarati, which often read more like a press release from Tesla than journalism. And, like Trump, Musk loves to throw digital Molotov cocktails on the internet. He went from aiming to be on the cover of magazines to help his business grow to giving the middle finger to every mainstream news outlet who didn’t parrot his vision of the world.
            </p>
            <p>
                On Twitter, he seemed to just want to be himself more too. At times on social media, Musk seems sane and collected, sharing tidbits about science and climate change. At other times he is erratic and irrational, tweeting things that seem to coddle the alt-right, men’s rights activists, and random conspiracy theorists. As his attacks against the conventional wisdom around coronavirus wore on earlier in the year, Musk ignored those who tried to point out how his understanding of COVID-19 was blatantly incorrect and how deadly the disease really is. The new Elon Musk didn’t care. Like a child covering his ears and yelling “la-la-la-la-la-la,” he simply didn’t want to hear it.
            </p>
            <p>
                While Twitter has proven to be a hotbed of chaos for Musk, during certain times of the year his habits on the platform played out like a Shakespearean drama. In the first week of June, for example, shortly after he and his girlfriend, the artist and singer Grimes, had their baby, Musk began following his ex-wife Justine Musk, then followed his other ex-wife Talulah Riley (they were married and divorced twice), and bizarrely, a few days later, unfollowed Grimes before re-following her again hours later. When Grimes later shared a thoughtful 274-character explanation of the name of their first child, “X Æ A-12”—a translation which includes references to “elven spelling,” the “unknown variable” of the letter x, emojis of swords, a “metal rat,” and the “SR-17” aircraft—Musk publicly responded that she had made a mistake and the plane was actually an “SR-71.” (“I am recovering from surgery and barely alive so may my typos b forgiven but, damnit,” Grimes responded. “That was meant to be profound.” Followed, of course, by a hedgehog emoji.
            </p>
            <p>
                Many people I’ve spoken to who have worked with Musk in the past or are close to him have pointed out that, from a financial and corporate perspective, Musk’s mission to block his detractors and to not care what others think of him—to be himself, jerk or otherwise—is working better than he, or anyone around him, could have imagined. This past year, Musk successfully launched two astronauts into orbit from the United States (the first in almost a decade), Tesla became the most valuable car company on the planet in July, and Musk is working toward implanting chips into people’s brains. Tesla also seemed poised to be inducted into the S&P 500, but a variety of factors, including Musk’s stock options, may have impeded it from making the cut. When I started reporting this story earlier this summer, Musk was worth half of what he is today, and while he’s disliked by the left, he is still idolized among the technorati.
            </p>
            <p>
                While it appears that Musk’s mission to say and do whatever he wants without caring about the results has worked out financially, there is another side to the story that those close to him, and especially Musk himself, are acutely aware of. Since around the Summer of 420, Musk has lost more than two dozen executives at Tesla, including three different general counsels, his director of engineering, director of sales, directors of finance, operations, accounting, production, and recruiting. His chief of staff, Sam Teller, who helped advise Musk with all things related to SpaceX, Tesla, and the Boring Company, also left after five years at Musk’s side. One of those former executives told me there were times Musk would say or tweet something that was just too embarrassing to even try to defend.
            </p>
            <p>
                Which brings us to the great irony of Elon Musk and his endless missions. They all have a duality to them, and Musk seems able to see only one side of the equation. His mission to colonize Mars, for example, is one that he envisions will save humanity, given that we will likely destroy Earth through climate change, or artificial intelligence, or some other cataclysmically awful human-inspired event. According to all the people I spoke to for this article, Musk thinks starting over somewhere else will give us an opportunity to do things better next time. He genuinely believes that he can build enough rockets that we could see 1 million people living on the red planet by 2050.
            </p>
            <p>
                But when we eventually end up on another planet, humanity is most likely to do there what we’ve done here: destroy whatever wonder we have built. Nowhere is that more on display than with Musk himself. Humans are capable of great things. Every once in a while, a human comes along and propels us forward by leaps and bounds. A human like Musk. But, at the same time, those humans are imperfect, even if we don’t want them to be. “They are flawed. They are not perfect. They are absolute extremes of themselves,” explained one of Musk’s former executives. If we end up on Mars, Musk will be there too, and he will bring his extremes with him. People will still disagree with each other. They will still argue about the way that world should be. If Twitter works on the red planet, Musk will still be blocking people who don’t agree with him. And his own personality defects won’t be left here on Earth.
            </p>
            <p>
                Musk, at times, can even acknowledge this himself. One former employee told me that once, this person asked Musk if he ever worried about losing his mind. Musk replied: “Does a crazy person ever look in the mirror and know that he’s crazy?” Perhaps this is really the most important mission Musk is on. To never have to answer that question.
            </p>
        </div>
    </article>
</html>